### ISSUE TITLE
Update Blogs adding Quantum Machine Learning

### ISSUE THREAD

**Issue by Anshikapal05** [Chandresh-Sharma/training-git#51]
Will update Quantum Machine Learning part which Combines principles of quantum computing and machine learning.It is beneficial for further knowledge as it is fast growing.

**Comment by Anshikapal05** [comment]
@Chandresh-Sharma Could you please assign to me and add hacktoberfest labels in it.
Would be really grateful to you!
Thank you.

**Comment by Chandresh-Sharma** [comment]
> @Chandresh-Sharma Could you please assign to me and add hacktoberfest labels in it. Would be really grateful to you! Thank you.

Sure
